<?php

namespace Application\Db\Model;

use Doctrine\ORM\EntityRepository;

/**
 * Board
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Board extends EntityRepository
{

}