<?php echo $this->doctype(); ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

    <title>Moodboard.io</title>
    
    <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/creative.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <!-- Scripts -->
         <?php echo $this->headScript()
              ->prependFile($this->basePath('js/bootstrap.min.js'))
              ->prependFile($this->basePath('js/jquery.min.js'))
              ->prependFile($this->basePath('js/creative.js'))
              ->prependFile($this->basePath('js/classie.js'))
              ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
              ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
           
         ; ?>
         
 
    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="https://use.typekit.net/sco8loq.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>

</head>

<body id="page-top">
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid primary">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Moodbox.io</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">
                            <i class="fa fa-refresh text-primary"></i>
                            <p>Refresh</p>
                        </a>
                    </li>
                    <li>
                        <input type="checkbox" name="toggle" id="toggle" onchange="valueChanged()">
                        <label for="toggle"></label>
                        <a><p>Collaborate</p></a>
                    </li>
                    <li>
                        <button href="#" class="btn btn-primary btn-xl">Export PDF</button>
                    </li>
                    <div class="copy-link" id="copy-link">
                        <p>Share your URL with your co-workers and start
                            collecting inspiration together.</p>
                        <input type="text" id="copyTarget" value="http://jsfiddle.net/CtH9k/">
                        <button id="copyButton" class="btn btn-primary">Copy</button>
                    </div>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <div class="container-fluid team">
            <p>Participants</p>
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="#page-top" class="btn btn-round btn-primary btn-xl page-scroll">Me</a>
                </li>
                <li>
                    <a href="#stefan" class="btn btn-round btn-primary btn-xl page-scroll">Stefan</a>
                </li>
                <li>
                    <a href="" class="btn btn-round btn-primary btn-xl">Dani</a>
                </li>
            </ul>
            <input type="checkbox" name="toggle" id="toggle2" onchange="valueChanged2()">
            <label for="toggle"></label>
        </div>
        <!-- /.container-fluid -->
    </nav>
    
    <?php echo $this->content; ?>
    
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x wow bounceIn"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/jquery.fittext.js"></script>
    <script src="js/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/creative.js"></script>

    <script src="https://npmcdn.com/imagesloaded@4.1/imagesloaded.pkgd.min.js"></script>
    <script src="https://npmcdn.com/masonry-layout@4.0/dist/masonry.pkgd.min.js"></script>

    <script>
        var $container = $('.masonry-container');
        $container.imagesLoaded( function () {
            $container.masonry({
                columnWidth: '.item',
                itemSelector: '.item'
            });
        });

        $('.like-button').click(function () {
            $(this).toggleClass("active");
        });

        document.getElementById("copyButton").addEventListener("click", function() {
            copyToClipboard(document.getElementById("copyTarget"));
        });

        function copyToClipboard(elem) {
            // create hidden text element, if it doesn't already exist
            var targetId = "_hiddenCopyText_";
            var isInput = elem.tagName === "INPUT" || elem.tagName === "TEXTAREA";
            var origSelectionStart, origSelectionEnd;
            if (isInput) {
                // can just use the original source element for the selection and copy
                target = elem;
                origSelectionStart = elem.selectionStart;
                origSelectionEnd = elem.selectionEnd;
            } else {
                // must use a temporary form element for the selection and copy
                target = document.getElementById(targetId);
                if (!target) {
                    var target = document.createElement("textarea");
                    target.style.position = "absolute";
                    target.style.left = "-9999px";
                    target.style.top = "0";
                    target.id = targetId;
                    document.body.appendChild(target);
                }
                target.textContent = elem.textContent;
            }
            // select the content
            var currentFocus = document.activeElement;
            target.focus();
            target.setSelectionRange(0, target.value.length);

            // copy the selection
            var succeed;
            try {
                succeed = document.execCommand("copy");
            } catch(e) {
                succeed = false;
            }
            // restore original focus
            if (currentFocus && typeof currentFocus.focus === "function") {
                currentFocus.focus();
            }

            if (isInput) {
                // restore prior selection
                elem.setSelectionRange(origSelectionStart, origSelectionEnd);
            } else {
                // clear temporary content
                target.textContent = "";
            }
            return succeed;
        }

//            $('#toggle').click(function() {
//                $("#copy-link").toggle(this.checked);
//            });

        function valueChanged()
        {
            if($('#toggle').is(":checked"))
                $("#copy-link").addClass('visible');
            else
                $("#copy-link").removeClass('visible');
        }

        function valueChanged2()
        {
            if($('#toggle2').is(":checked")) {
                $('.item').removeClass('col-md-3').addClass('col-md-2');
                $container.imagesLoaded(function () {
                    $container.masonry({
                        columnWidth: '.item',
                        itemSelector: '.item'
                    });
                });
            }

            else {
                $('.item').removeClass('col-md-2').addClass('col-md-3');
                $container.imagesLoaded(function () {
                    $container.masonry({
                        columnWidth: '.item',
                        itemSelector: '.item'
                    });
                });
            }
        }
    </script>

</body>

</html>
