<section>
        <div class="row masonry-container container-fluid">
            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <img src="https://images.unsplash.com/photo-1453974336165-b5c58464f1ed?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=12d0ef05e407b1c9c85ad9875ece1a13" alt="">
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">5 likes</span>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="https://images.unsplash.com/photo-1453857122308-5e78881d7acc?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=c02cc68e848cc645bd95d69c58e0df0b" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">5 likes</span>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="https://images.unsplash.com/photo-1452475168325-672188dc4dc3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=90ac1d6a1647efae8f2e547893d8cdec" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="https://images.unsplash.com/photo-1438979315413-de5df30042a1?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=f4e447e4fd3f59f41f8bf68e17f3d895" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="https://images.unsplash.com/photo-1430329429612-babb42f88673?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=1d30718749dca5ea5ca3351fedeb8f64" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <img src="https://images.unsplash.com/photo-1453974336165-b5c58464f1ed?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=12d0ef05e407b1c9c85ad9875ece1a13" alt="">
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">5 likes</span>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="https://images.unsplash.com/photo-1427435150519-42d9bcd0aa81?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=1896a40b338ccfb0d8ff7e5199e5ecd2" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="https://images.unsplash.com/photo-1453974336165-b5c58464f1ed?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=12d0ef05e407b1c9c85ad9875ece1a13" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">5 likes</span>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="https://images.unsplash.com/photo-1430329429612-babb42f88673?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=1d30718749dca5ea5ca3351fedeb8f64" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="https://images.unsplash.com/photo-1430329429612-babb42f88673?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=1d30718749dca5ea5ca3351fedeb8f64" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="https://images.unsplash.com/photo-1430329429612-babb42f88673?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=1d30718749dca5ea5ca3351fedeb8f64" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <img src="https://images.unsplash.com/photo-1430329429612-babb42f88673?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=1d30718749dca5ea5ca3351fedeb8f64" alt="">
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">5 likes</span>
                </div>
            </div><!--/.item  -->
        </div>
        <div class="container-fluid user-feed" id="stefan">
            <p>Stefan</p>
            <span>5 items</span>
        </div>
        <div class="row masonry-container">
            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div>

        </div>
    </section>
