<section>
        <div class="row masonry-container container-fluid">
            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <img src="img/biblie.jpeg" alt="">
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">5 likes</span>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="img/deer.jpeg" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">5 likes</span>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="img/girl.jpeg" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="img/rib.jpeg" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="img/girl.jpeg" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <img src="img/biblie.jpeg" alt="">
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">5 likes</span>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="img/rib.jpeg" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="img/deer.jpeg" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">5 likes</span>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="img/girl.jpeg" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="img/rib.jpeg" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="img/girl.jpeg" alt="">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">12 likes</span>
                </div>
                <div class="caption comment">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium.</p>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <div class="close-icon">
                        <i class="fa fa-trash"></i>
                    </div>
                    <img src="img/biblie.jpeg" alt="">
                    <div class="overlay"></div>
                    <button class="like-button">
                        <i class="fa fa-thumbs-up"></i>
                    </button>
                    <span class="likes">5 likes</span>
                </div>
            </div><!--/.item  -->
        </div>
        <div class="container-fluid user-feed" id="stefan">
            <p>Stefan</p>
            <span>5 items</span>
        </div>
        <div class="row masonry-container">
            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div><!--/.item  -->

            <div class="col-md-3 col-sm-6 item">
                <div class="thumbnail">
                    <img src="http://lorempixel.com/200/200/abstract" alt="">
                    <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, illum voluptates consectetur consequatur ducimus. Necessitatibus, nobis consequatur hic eaque laborum laudantium. Adipisci, explicabo, asperiores molestias deleniti unde dolore enim quas.</p>
                        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                </div>
            </div>

        </div>
    </section>
